# Generated by Django 6.1.1 on 2026-10-09 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', models.CharField(max_length=255)),
                ('valor_objetivo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ponderacion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='organizacion.responsable')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='organizacion.sede')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='resultados.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_calculo', models.DateField()),
                ('meta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='resultados.meta')),
            ],
        ),
    ]
