# Generated by Django 6.1.1 on 2026-10-09 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='nombre',
        ),
        migrations.AddField(
            model_name='actividad',
            name='accion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividad',
            name='aprobada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actividad',
            name='avance_aprobado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='corregida',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='espacio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='organizacion.espacio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividad',
            name='estado',
            field=models.CharField(default='pendiente', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividad',
            name='fecha',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividad',
            name='sede',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='organizacion.sede'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(default='general', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='organizacion.responsable'),
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('archivo_url', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('observacion', models.TextField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='actividades.actividad')),
            ],
        ),
        migrations.DeleteModel(
            name='Meta',
        ),
    ]
