# Generated by Django 6.1.1 on 2026-10-09 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=150)),
                ('fecha_comprometida', models.DateField()),
                ('prioridad', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=50)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos', to='organizacion.responsable')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos', to='organizacion.sede')),
            ],
        ),
    ]
