# Generated by Django 6.1.1 on 2026-10-09 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=100)),
                ('encargado', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=150)),
                ('especialidad', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsables', to='organizacion.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='espacios', to='organizacion.sede')),
            ],
        ),
    ]
